// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use multiversx_sc::proxy_imports::*;

pub struct FootballFieldRentalProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for FootballFieldRentalProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = FootballFieldRentalProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        FootballFieldRentalProxyMethods { wrapped_tx: tx }
    }
}

pub struct FootballFieldRentalProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> FootballFieldRentalProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    pub fn init<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
        Arg1: ProxyArg<BigUint<Env::Api>>,
    >(
        self,
        manager: Arg0,
        court_cost: Arg1,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .argument(&manager)
            .argument(&court_cost)
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> FootballFieldRentalProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn create_football_slot<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<u64>,
    >(
        self,
        start: Arg0,
        end: Arg1,
    ) -> TxTypedCall<Env, From, To, (), Gas, ()> {
        self.wrapped_tx
            .raw_call("createFootballSlot")
            .argument(&start)
            .argument(&end)
            .original_result()
    }

    pub fn participate_to_football_slot(
        self,
    ) -> TxTypedCall<Env, From, To, (), Gas, ()> {
        self.wrapped_tx
            .raw_call("participateToFootballSlot")
            .original_result()
    }

    pub fn cancel_football_slot(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("cancelFootballSlot")
            .original_result()
    }

    pub fn set_football_field_manager<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        new_manager: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("setFootballFieldManager")
            .argument(&new_manager)
            .original_result()
    }

    pub fn pay_court(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("payCourt")
            .original_result()
    }

    pub fn set_football_court_cost<
        Arg0: ProxyArg<BigUint<Env::Api>>,
    >(
        self,
        new_cost: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("setFootballCourtCost")
            .argument(&new_cost)
            .original_result()
    }

    pub fn confirm_slot(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("confirmSlot")
            .original_result()
    }

    pub fn get_slot_status(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, (Option<Slot<Env::Api>>, ManagedVec<Env::Api, ManagedAddress<Env::Api>>, BigUint<Env::Api>, ReservationStatus)> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getSlotStatus")
            .original_result()
    }
}

#[type_abi]
#[derive(TopEncode, TopDecode, NestedEncode, NestedDecode, Clone)]
pub struct Slot<Api>
where
    Api: ManagedTypeApi,
{
    pub start: u64,
    pub end: u64,
    pub payer: ManagedAddress<Api>,
    pub amount: BigUint<Api>,
    pub confirmed: ReservationStatus,
}

#[type_abi]
#[derive(TopEncode, TopDecode, NestedEncode, NestedDecode, PartialEq, Eq, Clone)]
pub enum ReservationStatus {
    Pending,
    Confirmed,
    Cancelled,
}
