// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            8
// Async Callback (empty):               1
// Total number of exported functions:  10

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    football_field_rental
    (
        init => init
        createFootballSlot => create_football_slot
        participateToFootballSlot => participate_to_football_slot
        cancelFootballSlot => cancel_football_slot
        setFootballFieldManager => set_football_field_manager
        payCourt => pay_court
        setFootballCourtCost => set_football_court_cost
        confirmSlot => confirm_slot
        getSlotStatus => get_slot_status
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
